name: Release

on:
  workflow_dispatch:
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TIME_STAMP: ""
    steps:
      - uses: actions/checkout@v4

      - name: Prepare build
        run: |
          timestamp=$(date '+%Y-%m-%d')
          echo "TIME_STAMP=$timestamp" >> $GITHUB_ENV

      - name: Zip directory
        run: |
          if [ ! -d "servant" ]; then
            mkdir servant
          fi
          zip -r servant.zip servant

          if [ ! -d "ce" ]; then
            mkdir ce
          fi
          zip -r ce.zip ce

          if [ ! -d "servant-color" ]; then
            mkdir servant-color
          fi
          zip -r servant-color.zip servant-color

          if [ ! -d "ce-color" ]; then
            mkdir ce-color
          fi
          zip -r ce-color.zip ce-color
    
      - name: Create release
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2.2.1
        with:
          tag_name: "${{ env.TIME_STAMP }}"
          name: "${{ env.TIME_STAMP }}"
          body: |
            > [!TIP]
            > The colored version will be used for the colored template matching.
            > It will provide better results for selecting the correct template.
            > In exchange, it would have increased the size of the release.
            >
            > If you want to save space, you can use the non-colored version.
          files: |
            servant.zip
            ce.zip
            servant-color.zip
            ce-color.zip
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}